### ISSUE TITLE
npm install does nothing

### ISSUE THREAD

**Issue by Tyguy7** [resource/fabricator#106]
I don't know what the deal is here, but running npm install immediately quits and makes no changes.

This happens after using yo fabricator, and git clone methods both.

Running npm start fails because the npm install command that runs first does nothing, causing dependency missing errors.

**Comment by Tyguy7** [comment]
This on Ubuntu 14.04, latest node.js

**Comment by LukeAskew** [comment]
What version of node and npm?

People have reported issues using npm < 2.0

**Comment by Tyguy7** [comment]
Yes, that's it, my npm is not up to date.  Thanks.
