### ISSUE TITLE
Themes and adding current index to iteration helper

### ISSUE THREAD

**Issue by jdelight** [resource/fabricator#92]
Hi @LukeAskew,

Just playing with the iteration helper and adapted it slightly to include the current index. 

I'm wondering how Fabricator could help with creating themed components (now that maps support is in node-sass).
One approach is a simple numeric theme `.theme-1 { ... }` `.theme-2 { ... }` and the iterator helper is perfect for that. Here's an example:

I've updated the iteration helper to include current index (http://handlebarsjs.com/block_helpers.html)
```javascript
/**
 * Block iteration
 * @description Repeat a block a given amount of times.
 * @example
 * {{#iterate 20}}
 *   <li>List Item {{@index}}</li>
 * {{/iterate}}
 */
Handlebars.registerHelper('iterate', function (n, block) {
	var accum = '', data;
	for (var i = 0; i < n; ++i) {
		if (block.data){
			data = Handlebars.createFrame(block.data || {});
			data.index = i;
		}
		data.index = i;
		accum += block.fn(i, {data: data});
	}
	return accum;
});

```

which lets you do this
```
       {{#iterate 3}}
        <div class="theme-{{@index}}">
            <div class="header">
                some text
            </div>
            <div class="footer">
                some text
            </div>
        </div>
        {{/iterate}}
```

Some sass to generate themes - could be improved but you get the idea.
```sass
$themes: (
        (
                header: #b06,
                text: #334,
                footer: #666777,
        ),
        (
                header: #333,
                text: #fff,
                footer: #f33,
        ),
        (
                header: #999,
                text: #444,
                footer: #f83,
        )
);

.header {
    @each $theme in $themes {
        .theme-#{index($themes, $theme)} & {
            background: map-get($theme, 'header')
            color: map-get($theme, 'text')
        }
    }
}
```

**Comment by LukeAskew** [comment]
Thanks!

Mind putting the iteration stuff in a pull request?

I need to think some on the theming concept. I need to update the `_variables.scss` file now that sourcemaps works in node-sass. Might be a good opportunity to incorporate some of your thoughts.

**Comment by jdelight** [comment]
Sounds good - PR open here #93 :+1:
