### ISSUE TITLE
Using only div's for fabricator html

### ISSUE THREAD

**Issue by dietergeerts** [resource/fabricator#95]
Hi, We are creating our toolkit and want/have/need to work as semantic as possible. This also means using as less classes as possible and instead using the html elements correctly with their role attribute. Doing this causes trouble for the toolkit itself, as for example, the nav becomes troubled as of our css code for our nav structure. Would it be possible to refactor fabricator to use only div's as this will not interfere with the toolkit css?

**Comment by haydenhancock** [comment]
Agreed! I think this would be a good feature. Something similar to semantic-ui.com would be ideal.
